# Generated by Django 5.2.4 on 2025-08-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icloud_device_name',
            field=models.CharField(blank=True, help_text='追跡するデバイス名', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='icloud_email',
            field=models.EmailField(blank=True, help_text='iCloud位置情報取得用のApple ID', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='icloud_password_encrypted',
            field=models.TextField(blank=True, help_text='暗号化されたiCloudパスワード'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_known_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_known_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_tracking_enabled',
            field=models.BooleanField(default=False, help_text='位置情報追跡を有効にする'),
        ),
    ]
