# Generated by Django 5.2.4 on 2025-08-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_icloud_device_name_user_icloud_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='GoogleアカウントのユニークID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.URLField(blank=True, help_text='Googleプロフィール画像URL', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False, help_text='Google認証で作成されたアカウント'),
        ),
    ]
