# Generated by Django 5.2.5 on 2025-08-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "store_type",
                    models.CharField(
                        choices=[("convenience", "コンビニ"), ("pharmacy", "薬局")],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("opening_hours", models.TextField(blank=True)),
                ("chain_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="stores_stor_latitud_161be0_idx",
                    ),
                    models.Index(
                        fields=["store_type"], name="stores_stor_store_t_93515a_idx"
                    ),
                ],
            },
        ),
    ]
