# Generated by Django 5.2.5 on 2025-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name="store",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
