# Generated by Django 5.2.5 on 2025-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_store_latitude_alter_store_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="latitude",
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name="store",
            name="longitude",
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
