# Generated by Django 5.2.4 on 2025-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='store',
        ),
        migrations.AddField(
            model_name='reminder',
            name='store_type',
            field=models.CharField(choices=[('convenience_store', 'コンビニ'), ('pharmacy', '薬局')], default='convenience_store', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
