# Generated by Django 5.2.4 on 2025-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remove_reminder_store_reminder_store_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='store_type',
            field=models.CharField(choices=[('convenience', 'コンビニ'), ('pharmacy', '薬局')], default='convenience', max_length=20),
        ),
    ]
